const fs = require('fs');
const path = require('path');

function loadEnv(file) {
  const result = {};
  if (!fs.existsSync(file)) return result;
  for (const line of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const m = trimmed.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (!m) continue;
    let value = m[2].trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    result[m[1]] = value;
  }
  return result;
}

const env = loadEnv(path.join(__dirname, '..', '.env'));

const apiKey =
  process.env.YOUTUBE_API_KEY ||
  env.YOUTUBE_API_KEY ||
  '';

const playlistId =
  process.env.PLAYLIST_ID ||
  env.PLAYLIST_ID ||
  '';

if (!apiKey || !playlistId) {
  throw new Error('Missing YOUTUBE_API_KEY or PLAYLIST_ID');
}

const content =
  '// Generated by scripts/gen-config.js - do not edit manually\n' +
  'const YOUTUBE_API_KEY = ' + JSON.stringify(apiKey) + ';\n' +
  'const PLAYLIST_ID = ' + JSON.stringify(playlistId) + ';\n';

fs.writeFileSync(path.join(__dirname, '..', 'js', 'config.js'), content);
console.log('js/config.js generated');
